//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelSoloApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class BookingFeedback
    {
        public int Id { get; set; }
        public short Rating { get; set; }

        public int Booking_Id { get; set; }

        [ForeignKey("Booking_Id")]
        public virtual Booking Booking { get; set; }
    }
}
